packages:
  - .

nodeLinker: hoisted
autoInstallPeers: false
minimumReleaseAge: 0

allowBuilds:
  cloudflared: true
  cpu-features: true
  node-pty: true
  protobufjs: true
  ssh2: true

fetchTimeout: 600000
